name: PlayerSettings
version: 4.6
main: me.limbo56.settings.PlayerSettings
author: lim_bo56
softDepend: ['icJukeBox', 'Citizens']
commands:
      settings:
           description: Main command of the plugin!