name: PlayerSettings
version: ${project.version}
main: me.limbo56.settings.PlayerSettings
author: lim_bo56
softDepend: ['icJukeBox']
commands:
      settings:
           description: Main command of the plugin!