#________________________________                               
#                                | 
#           Main Menu            |
#         Configuration          |
#________________________________|
MainMenu:
       #The name that will be displayed on the menu.
       Name: "MenuPreferences" 
       #Choose wether or not to have glass on the menu.
       Glass: true
       #This wil me the displayed name on the player preferences menu item.
       PlayerPreferencesItemName: "PlayerPreferences"
       #This wil me the displayed name on the lobby preferences menu item.
       LobbyPreferencesItemName: "LobbyPreferences"
       #The item that will be on the menu.
       #You can find all the item names at...
       #http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/mods-discussion/1341837-complete-item-list-as-a-c-java-enum
       PlayerPreferencesItem: SKULL_ITEM
       LobbyPreferencesItem: BEACON
#________________________________                               
#                                | 
#    PlayerPreferences Menu      |
#         Configuration          |
#________________________________|	
PlayerPreferences:
       #The name that will be displayed on the menu.
       Name: "PlayerPreferences"
       #Choose wether or not to have glass on the menu.
       Glass: true
       #This wil me the displayed name on the speed item.
       SpeedItemName: "&9Speed"
       #This wil me the displayed name on the jump item.
       JumpItemName: "&aJump"
       #This wil me the displayed name on the fly item.
       FlyItemName: "&5Fly"       
       #This wil me the displayed name on the vanish item.
       VanishItemName: "&cVanish"
       #The item that will be on the menu.
       #You can find all the item names at...
       #http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/mods-discussion/1341837-complete-item-list-as-a-c-java-enum
       SpeedItem: SUGAR
       JumpItem: DIAMOND_BOOTS
       FlyItem: FEATHER
       VanishItem: LEASH
#________________________________                               
#                                | 
#     LobbyPreferences Menu      |
#         Configuration          |
#________________________________|		   
LobbyPreferences:
       #The name that will be displayed on the menu.
       Name: "LobbyPreferences"
       #Choose wether or not to have glass on the menu.	   
       Glass: true
       #This wil me the displayed name on the fly item.	   
       StackerItemName: "&bStacker"
       #This wil me the displayed name on the visibility item.
       VisibilityItemName: "&3Visibility"
       #This wil me the displayed name on the chat item.
       ChatItemName: "&6Chat"
       #The item that will be on the menu.
       #You can find all the item names at...
       #http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/mods-discussion/1341837-complete-item-list-as-a-c-java-enum
       StackerItem: MAGMA_CREAM
       VisibilityItem: EYE_OF_ENDER
       ChatItem: PAPER
#________________________________                               
#                                | 
#     Dye Item Configuration     |
#________________________________|	   
DyeItem:
      #The name of the item that will be displayed when an option is enabled.
      enabled: "&aOn"
      #The lore of the item that is displayed when an option is enabled.
      enabled-lore: "&fClick to &aenable"
      #The name of the item that will be displayed when an option is disabled.
      disabled: "&cOff"
      #The lore of the item that is displayed when an option is disabled.
      disabled-lore: "&fClick to &cdisable"
#________________________________                               
#                                | 
#         Go Back Item           |
#        Configuration           |
#________________________________|	
GoBack:
      #This wil me the displayed name on the back item.
      BackItemName: '&e&lGo Back'
      #The item that will be on the menu.
      #You can find all the item names at...
      #http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/mods-discussion/1341837-complete-item-list-as-a-c-java-enum
      BackItem: ARROW
      #Put this on true if you want the arrow of the menus to preform a command when clicked if not put it to false.
      prefrom-cmd: false
      #If the boolean above is true this commando will preform when the player clicks the arrow on the lobby preferences menu.
      #Do not put the / and then the command type only the command.
      LobbyPreferences-cmd: ""
      #If the boolean above is true this commando will preform when the player clicks the arrow on the player preferences menu.
      #Do not put the / and then the command type only the command.
      PlayerPreferences-cmd: ""
      
#________________________________                               
#                                | 
#       All Chat Messages        | 
#         Configuration          |
#________________________________|	
Messages:
      #This message is sended to the player when thet don't have permissions to do something.
      no-permissions: '&c&lYOU &7don`t have permissions to do this.'
      #The message that will be sended to the player when he tries to stack another player but he has stacker disabled.
      player-stacker-disabled: '&c&lYOU &7have stacker disabled.'
      #The message that will be sended to the player when he tries to stack another player but the player has stacker disabled.
      target-stacker-disabled: '&c&lTHAT &7person has stacker disabled.'
      #This message is sended when the player has chat disabled and types something in the chat.
      chat-disabled: '&c&lYOU &7have the chat disabled, enable it at the preferences.'
      #Put this on true if you want to recive an update message if not put it on false.
      update-msg: true
#________________________________                               
#                                | 
#         Enabled Worlds         | 
#         Configuration          | #These are the world that the plugin will work.
#________________________________|	
Worlds:
 - world