name: LobbyandPlayerPreferences
version: 2.7
main: me.lim_bo56.lnpp.MainPreferences
author: lim_bo56
commands:
      preferences: 
           description: Opens the preferences main menu!
           aliases: pref 
      preferencesLobby:
           description: Opens the lobby preferences menu!
      preferencesPlayer:
           description: Opens the player preferences menu!