name: LobbyAndPlayerPreferences
version: 1.1
main: LobbyPlayerMain.Main
author: lim_bo56
commands:
    preferences:
      description: Opens the preferences menu!
    pref:
      description: Opens the preferences menu!
    preferencesPlayer:
      description: Opens the player preferences menu!
    preferencesLobby:
      description: Opens the lobby preferences menu!
    preferences-reload:
      description: Reloads the plugins config!	