#
#                   Database Information
#
# If you want to disable it, put false where it says 'enable'.
#
MySQL:
    enable: true
    host: localhost
    port: 3306
    database: playersettings
    name: root
    password: